// 28/06/2025
/* EXCLUIDOS
const IcoLixo=(Clss)=>`<svg class="${Clss}" xmlns="http://www.w3.org/2000/svg" width="16.25mm" height="20mm" viewBox="0 0 84.85 104.43">
<path d="M13.05 90.36l0 -57.72 58.74 0 0 57.72c0,4.86 -2.68,7.55 -7.55,7.55l-43.65 0c-4.86,0 -7.55,-2.68 -7.55,-7.55zm42.43 -41.81l0 39.98c0,1.48 1.42,2.86 3.67,2.86 1.27,0 2.86,-1.58 2.86,-2.86l0 -39.98c0,-1.48 -1.41,-2.86 -3.67,-2.86 -1.27,0 -2.86,1.58 -2.86,2.86zm-32.64 0l0 39.98c0,1.48 1.42,2.86 3.67,2.86 1.27,0 2.86,-1.58 2.86,-2.86l0 -39.98c0,-1.48 -1.41,-2.86 -3.67,-2.86 -1.27,0 -2.86,1.58 -2.86,2.86zm16.32 0l0 39.98c0,1.48 1.42,2.86 3.67,2.86 1.27,0 2.86,-1.58 2.86,-2.86l0 -39.98c0,-1.48 -1.41,-2.86 -3.67,-2.86 -1.27,0 -2.86,1.58 -2.86,2.86zm-28.76 -28.96l64.05 0c5.1,0 5.1,6.53 0,6.53l-64.05 0c-5.1,0 -5.1,-6.53 0,-6.53zm22.23 -9.18c0,-2.5 1.37,-3.88 3.88,-3.88l11.83 0c4.37,0 3.88,3.61 3.88,6.53l-19.58 0 0 -2.65zm-6.53 -4.49l0 7.14 -20.19 0c-2.83,0 -5.92,3.08 -5.92,5.92l0 7.75c0,2.78 2.77,5.92 6.53,5.92l0 59.56c0,6.16 6.08,12.24 12.24,12.24l47.32 0c6.16,0 12.24,-6.08 12.24,-12.24l0 -59.56c3.76,0 6.53,-3.14 6.53,-5.92l0 -7.75c0,-2.83 -3.08,-5.92 -5.92,-5.92l-20.19 0c0,-4.7 0.76,-8.54 -1.88,-11.18 -0.81,-0.81 -2.51,-1.88 -4.04,-1.88l-20.81 0c-2.83,0 -5.92,3.08 -5.92,5.92z"/>
</svg>`

const IconLogin=(Clss,Cor1)=>`<svg class="${Clss}" xmlns="http://www.w3.org/2000/svg" width="70.7319mm" height="70.7319mm" viewBox="0 0 7055.58 7055.58"
  <path style="fill:${Cor1}" d="M3527.79 0c1948.35,0 3527.8,1579.45 3527.8,3527.79 0,1948.35 -1579.45,3527.8 -3527.8,3527.8 -1948.34,0 -3527.79,-1579.45 -3527.79,-3527.8 0,-1948.34 1579.45,-3527.79 3527.79,-3527.79zm-9.64 4103.28c1030.45,0 1930.07,559.8 2411.56,1391.84 439.2,-535.58 702.86,-1220.64 702.86,-1967.33 0,-1714.71 -1390.06,-3104.77 -3104.78,-3104.77 -1714.71,0 -3104.77,1390.06 -3104.77,3104.77 0,740.3 259.26,1419.97 691.72,1953.51 483.42,-824.37 1378.7,-1378.01 2403.41,-1378.01zm0.14 -2781.66c724.31,0 1311.48,587.16 1311.48,1311.48 0,724.31 -587.16,1311.48 -1311.48,1311.48 -724.31,0 -1311.48,-587.16 -1311.48,-1311.48 0,-724.31 587.16,-1311.48 1311.48,-1311.48z"/>
</svg>
`
*/



// Template String__________________________________________________
// não ta sendo usada nenhuma daqui em 'OrçamentoGRAFF' todas são de NexBee

const Tm_HLogo=(e,Qnt,CSS,MaxW)=>{
    const hov = S(e).Coten('Hov') ; const HOV = hov===true
    S(e).Rmv('Hov')
    const Inner = $Inn(e)

    $(e).innerHTML = For(Qnt).map(e=>`
    <style>
        @media(max-width:${MaxW}px){#H_Logo${e+1}{display:${e+1==1?'none':'flex'}}}
        @media(min-width:${MaxW}px){#H_Logo${e+1}{display:${e+1==1?'flex':'none'}}}
    </style>
    <img id="H_Logo${e+1}" class="${HOV?'Hov':''}" style="${VV_CSS(CSS)}" onclick="NavPag('#PagHOME')" src="./img/H_Logo${e+1}.webp">
    `).join('') + `<h1 class="${HOV?'Hov':''}">${Inner}</h1>`
}
const Tm_HPesq=(e,css1,css2,Class)=>{$(e).innerHTML = `
    <input class="${Class} w100" style="${VV_CSS(css1)};cursor:text;${Class==='Kina'?'border-radius:0px':''}" name="8" type="text" onkeyup="Pesquisar(this.value)" placeholder="Pesquisar...">
    <img class="Abslt HOV" style="${VV_CSS(css2)}" src="../000_Bibliotecas/Kit_Icon/Icon_Lupa.svg">`
}
const Tm_Nav=(e,Off,ObjNav)=>{
    if(Off){$(e).innerHTML = ''}
    else{$(e).innerHTML = ObjEtr(ObjNav).map(([e,v])=>`<p class="Rltv HOV">${v===0?``:`<a class="Abslt Notfi">${v}</a>`}<img src="./img/nav_${e}.svg" class="SvgHov HTML_Nav_Img" title="Seu: ${Dbrev[e]}" onclick="NavPag('#Pag${e}',this);SibQSl(this,'a')?SibQSl(this,'a').remove():null"></p>`).join('')}
}
const Tm_HLgin=(e,Off,Src)=>{
    const hov = S(e).Coten('Hov') ; const HOV = hov===true
    S(e).Rmv('Hov')
    const Inner = $Inn(e)

    $(e).innerHTML = `
        ${Off?'<p id="h_Cdstr" class="Ct Hov" onclick="MdalShow("#MdalLgin")">'+Inner+'</p>':''}
        <div class="Rltv">
        <img id="h_Foto" class="${HOV?'Hov':''}" src="${Src}">
        <img id="h_Levl" class="Abslt ${HOV?'Hov':''}" src="./img/Level.svg" onload="NoneTruE('#h_Levl',${Off})">
        </div>`

}
function Tm_HMais(e,Array){
    const ObjKey = {
        'Troc':`<div class="Start" onclick="MdalShow('#MdalLgin')">     <img src="./img/Mais_Troc.svg"><a> Trocar de Conta  </a></div>`,
        'Edit':`<div class="Start" onclick="MdalShow('#EditarPerfil')"> <img src="./img/Mais_Edit.svg"><a> Editar Perfil    </a></div>`,
        'Cnfg':`<div class="Start" onclick="MdalShow('#ConfigPag')">    <img src="./img/Mais_Cnfg.svg"><a> Configurações    </a></div>`,
        'Help':`<div class="Start" onclick="NavPag('#PagSUPORTE')">     <img src="./img/Mais_Help.svg"><a> Central de Ajuda </a></div>`,
        'LOff':`<div class="Start" onclick="LogOff()">                  <img src="./img/Mais_LOff.svg"><a> Sair             </a></div>`,
        'Term':`<div><p>Confira os <a class="Link">Termos de Serviço</a> e as <a class="Link">Política de Privacidade       </a></p></div>`,
    }
    $(e).innerHTML = Array.map(e=>ObjKey[e]).join('')
}
function Tm_Notif(e,Off,Obj){
    $(e).innerHTML = '<div id="Notifics" class="Fx w100 Cl">'+ Obj.map((e,x)=>{
            return `<div class="Notif velocitylento ppt Rltv Start w90 Kina A-T" name="10" style="top: ${x*60}px;">
                <img src="./img/Icon_Sino.svg">
                <p style="font-size: 15px;">${Dbrev_Notif[e]}</p>
                <div class="Abslt Ct X" onclick="X_Notif(Pai($(this)))"><img src="./img/Icon_X.svg"></div>
    </div>`}).join('') + '</div>'
}
async function ExibeNotifi(){
    await Delay(1)
    for (const e of $$('.Notif')){Add(e,'Poses');await Delay(0.5)}
    await Delay(1)
    $$('.Notif').forEach(e=>{Rmv(e,'velocitylento')})
}
async function X_Notif(Div){
    await AnimeProp(Div,{'left':500,'opacity':0},0.3,true)
    Div.remove()
    $$('.Notif').forEach((e,x)=>{AnimeProp(e,{'top':x*60},0.3,false)})
}

const Fonts = ["Arial", "Courier New", "Georgia", "Times New Roman", "Verdana", "Comic Sans MS", "Trebuchet MS", "Impact", "Lucida Console", "Tahoma", "Helvetica", "Palatino Linotype", "Frank Ruhl Libre", "Montserrat", "Open Sans"]
const KitFonts = [
    'advent-Bd1',
    'advent-Bd2',
    'advent-Bd3',
    'advent-Lt1',
    'advent-Lt2',
    'advent-Lt3',
    'advent-Re',
    'Almarose-Black',
    'Almarose-Bold',
    'Almarose-ExtraBlack',
    'Almarose-Extrabold',
    'Almarose-Light',
    'Almarose-Medium',
    'Almarose-Regular',
    'Almarose-Semibold',
    'Almarose-Thin',
    'Anja Eliane accent002',
    'arial-rounded-mt-bold',
    'Balbek-Personal Use Only',
    'BebasNeue-Regular',
    'BebasNeue-Regular',
    'Dunkin Bold',
    'Dunkin Sans Bold',
    'EngraversGothic BT',
    'Exotc350 Bd BT Bold',
    'Exotc350 DmBd BT Demi-Bold',
    'Futura Bk BT Book',
    'Futura Bold BT',
    'Futura Bold Condensed BT',
    'Futura Light Condensed BT',
    'Futura Md BT Bold',
    'Futura Md BT Medium',
    'Futura Medium Condensed BT',
    'Futura-Condensed-Bold',
    'Futura-Condensed-Normal',
    'Futura-Condensed-Thin',
    'Futura-CondensedExtraBold-Th',
    'Futura-CondensedLight-Normal',
    'Futura-CondensedLight-Thin',
    'Futura-Normal',
    'FuturaCnd-Bold',
    'FuturaCnd-Norma',
    'FuturaCondLightE Regular',
    'Geometr212 BkCn BT Book',
    'Geometr212 BkCn BT Heavy',
    'Geometr415 Blk BT Black',
    'Geometr706 BlkCn BT Black',
    'GlacialIndifference-Bold',
    'GlacialIndifference-Regular',
    'Gotham Black Regular',
    'gotham-black',
    'holomdl2',
    'Humanst521 BT Bold',
    'Humanst521 BT Roman',
    'Humanst521 Lt BT Light',
    'Humnst777 BlkCn BT Black',
    'Humnst777 BT Roman',
    'Humnst777 Cn BT Bold',
    'Humnst777 Cn BT',
    'Humnst777 Lt BT Light',
    'IN901XKI',
    'Insanibc',
    'Insanibu',
    'integral-cf-medium',
    'Netraly',
    'neuzeitgrotblaextcon',
    'NewsGoth BT Bold',
    'NewsGoth BT Roman',
    'NewsGoth Lt BT Light',
    'ntailu',
    'ntailub',
    'OCR-B 10 BT',
    'phagspa',
    'phagspab',
    'Square721 BT Bold',
    'Square721 BT Roman',
    'Square721 Cn BT Bold',
    'Square721 Cn BT Roman',
    'Swis721 Blk BT Black',
    'Swis721 BlkCn BT Black',
    'Swis721 BT Bold',
    'Swis721 BT Roman',
    'Swis721 Cn BT Bold',
    'Swis721 Cn BT Roman',
    'Swis721 Hv BT Heavy',
    'Swis721 Lt BT Light',
    'Swis721 LtEx BT Light',
    'Swis721 WGL4 BT Bold',
    'Swis721 WGL4 BT Roman',
    'taile',
    'taileb',
    'Black-coffee-shadow',
    'Black-coffee',
    'CFGlitchCity-Regular',
    'CoffeCake',
    'Empires',
    'Freehand521 BT',
    'Gloomy Things',
    'Jacksilver',
    'Jamstreet Graffiti',
    'KOMIKAX_',
    'Malvie Trial',
    'MARSNEVENEKSK-Clean',
    'Mermaid Babies',
    'Mustard Smile',
    'Sandler Trial',
    'SOUTH-CREW',
    'Starlight',
    'Starlight',
    'Study Alone',
    'Thunder Bold',
    'Trolls Movie Font',
    'True Lies',
    'waltograph42',
    'waltographUI',
    'whoa!',
    'Fluo Gums',
    'GAGARIN_',
    'GAGASM__',
    'Gobold Blocky Regular',
    'Good Morning',
    'Jackpot Demo',
    'KGHAPPYSolid',
    'Legend M54',
    'Magnificent Personal Use',
    'Amsterdam',
    'April June',
    'Austria',
    'Bacalisties',
    'Blacksword',
    'boutiera-regular',
    'BrushScriptOpti-Regular',
    'buttercup_sample',
    'Caroline',
    'Contoursy Free',
    'Cream Cake',
    'Delight Sunset',
    'dk-combustible-regular',
    'Embassy BT',
    'exmouth',
    'FontsFree-Net-MoonTime-Regular-1',
    'Gillian Rode',
    'Halimun',
    'harlow-solid-std',
    'Howell Rode',
    'Kaufmann BT',
    'LOKICOLA',
    'Madina',
    'Manly Signature Regular',
    'Maria Aishane Script',
    'Maria Aishane Script',
    'Maria_lucia',
    'Pantherdam Signature',
    'Pinky Promise',
    'PinkyPromise',
    'Ruthligos',
    'Streamster',
    'Summer Lightning Demo',
    'The Golden Elephant',
    'The Yoshi',
    'TypoUpright BT',
    'Weather Sunday - Personal Use',
    'Meatloaf Solid',
    'PWYummyDonuts',
    'Quark Cheese - Personal Use',
    'Quillain (DEMO)',
    'Quillain (DEMO)',
    'RifficFree-Bold',
    'Rightland',
    'Run! Demo',
    'aachen-bold',
    'AgreloyInT3',
    'Ancient Medium',
    'atwriter',
    'belwe-std-condensed',
    'BerkshireSwash-Regular',
    'bernard-mt-std-condensed',
    'Bodoni Bd BT Bold',
    'Bodoni Bk BT Book',
    'CentSchbkCyrill BT Bold Italic',
    'CentSchbkCyrill BT Bold',
    'CentSchbkCyrill BT Italic',
    'CentSchbkCyrill BT Roman',
    'Century Oldstyle Bold',
    'Century Oldstyle Italic',
    'Century Oldstyle Regular',
    'Century725 Cn BT',
    'Century751 BT Italic',
    'Century751 BT Roman',
    'Century751 No2 BT Bold Italic',
    'Century751 No2 BT Bold',
    'Century751 No2 BT Italic',
    'Century751 No2 BT Roman',
    'Century751 SeBd BT Semi Bold Italic',
    'Century751 SeBd BT Semi Bold',
    'Clarendon Blk BT Black',
    'Clarendon BT Bold',
    'Clarendon BT Roman',
    'Clarendon Lt BT Light',
    'Cloister Oldstyle Roman',
    'CloisterBlack',
    'DeVinne Txt BT',
    'Edensor-FREE',
    'FE-FONT',
    'FONTLERO',
    'GeoSlab703 Md BT Bold',
    'GeoSlab703 Md BT Medium',
    'GeoSlab703 MdCn BT Bold',
    'GeoSlab703 MdCn BT Medium',
    'Home Christmas',
    'Hundo',
    'IFC INSANE RODEO BOLD Bold',
    'IFC INSANE RODEO',
    'MADEAvenuePERSONALUSE-Regular',
    'MAK-bold',
    'MAK',
    'News701 BT Bold',
    'News701 BT Italic',
    'News706 BT Bold',
    'OCR-A BT',
    'Olondona',
    'PirataOne-Regular',
    'PlateGtFourMTStd-Bd',
    'Qeilab',
    'RalstedaBold-d9d56',
    'RalstedaExtralight-L3vAg',
    'RalstedaHeavy-gxX2Y',
    'RalstedaLight-X3RXo',
    'RalstedaMedium-owAxV',
    'RalstedaRegular-4Bqy9',
    'Saddlebag',
    'Schadow BT Bold',
    'Schadow BT Roman',
    'Seagram tfb',
    'symbol',
    'TequilaSunrise-Regular',
    'TEXAT BOLD PERSONAL USE___',
    'TrajanPro-Bold',
    'TrajanPro-Regular',
    'VarsityTeam-Bold',
    'VASTN___',
    'Smartphone Color Pro',
    'Social Logos',
    'Splatch',
    'Stella Demo',
    'Stella Demo',
    'airstrike',
    'airstrike3d',
    'airstrikeacad',
    'airstrikeb3d',
    'airstrikebold',
    'airstrikebullet',
    'airstrikecond',
    'airstrikeexpand',
    'airstrikegrad',
    'airstrikehalf',
    'airstrikelaser',
    'airstrikeout',
    'Clark Bold Hollow',
    'Clark Bold',
    'Clark Hollow',
    'Clark',
    'DEADJIM',
    'Digital-Desolation-Plus',
    'Dihil',
    'Elektronik Italic',
    'Elektronik',
    'FontsFree-Net-Nura-ExtraLight',
    'High Speed',
    'Hindsight 2020',
    'hyperspace-race-extended-heavy',
    'Inlanders Demo',
    'Kardust TS Condensed Bold Italic',
    'KITCHENPOLICE',
    'LinkStart',
    'osaka-re',
    'paladins',
    'paladins3d',
    'paladinsgrad',
    'paladinslaser',
    'paladinsout',
    'paladinsstraight',
    'pricedown bl',
    'Reckoner',
    'Reckoner_Bold',
    'Rektec',
    'SOLVAST',
    'Square',
    'SwipeRaceDemo',
    'techno_hideo',
    'Vudotronic',
    'zrnic rg',
    'The Blacklist',
    'Type Icons',
    'aAttackGraffiti',
    'Comix Loud',
    'Dunkin Sans',
    'Dunkin',
    'Gemstone',
    'GROBOLD',
    'Irresponsible Direction',
    'Karate',
    'lastninja',
    'Minnie',
    'mvboli',
    'Neonblitz',
    'PlazaITC-Normal',
    'Rockit',
    'RUSTY ATTACK DEMO Regular',
    'seasideresortnf.regular',
    'shanghai',
    'TheGeorgia',
    'varsity_regular',
    'Wicked Mouse Demo',
    'xilosa',
]